open keyword "C:\Users\Kayleigh\Documents\HVI share\HVI\LS-OPT_test\X-optimization\mesh.key"
Time to read keyword file = 0.086 seconds
Warning - SECTION 1 not found:
  Referenced in *PART ID = 1
Warning - MAT 2 not found:
  Referenced in *PART ID = 1
Warning - EOS 1 not found:
  Referenced in *PART ID = 1
Warning - SECTION 2 not found:
  Referenced in *PART ID = 2
Warning - MAT 1 not found:
  Referenced in *PART ID = 2
Warning - EOS 2 not found:
  Referenced in *PART ID = 2
Time to process element data = 0.078 seconds
Finished reading model
Save Config. parameters to file C:\Users\Kayleigh\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
