openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.312 seconds
Time to process element data = 0.062 seconds
Finished reading model
home
displayentity Boundary Spc off all
displayentity Boundary Spc on 1
displayentity Boundary Spc off all
displayentity Boundary Spc off all
displayentity Boundary Spc on 2
displayentity Boundary Spc off all
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
