openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.312 seconds
Warning -Duplicate keyword: SOLID_ELEM input with ID=9879 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 2 from file lsppout
Data input seq. 7974 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9880 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 3 from file lsppout
Data input seq. 7975 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9881 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 4 from file lsppout
Data input seq. 7976 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9882 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 5 from file lsppout
Data input seq. 7977 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9883 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 6 from file lsppout
Data input seq. 7978 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9884 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 7 from file lsppout
Data input seq. 7979 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9885 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 8 from file lsppout
Data input seq. 7980 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9886 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 9 from file lsppout
Data input seq. 7981 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9887 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 10 from file lsppout
Data input seq. 7982 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9888 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 11 from file lsppout
Data input seq. 7983 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9889 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 12 from file lsppout
Data input seq. 7984 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9890 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 13 from file lsppout
Data input seq. 7985 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9891 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 14 from file lsppout
Data input seq. 7986 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9892 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 15 from file lsppout
Data input seq. 7987 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9893 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 16 from file lsppout
Data input seq. 7988 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9894 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 17 from file lsppout
Data input seq. 7989 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9895 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 18 from file lsppout
Data input seq. 7990 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9896 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 19 from file lsppout
Data input seq. 7991 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9897 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 20 from file lsppout
Data input seq. 7992 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9898 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 21 from file lsppout
Data input seq. 7993 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9899 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 22 from file lsppout
Data input seq. 7994 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9900 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 23 from file lsppout
Data input seq. 7995 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9901 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 24 from file lsppout
Data input seq. 7996 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9902 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 25 from file lsppout
Data input seq. 7997 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9903 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 26 from file lsppout
Data input seq. 7998 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9904 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 27 from file lsppout
Data input seq. 7999 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9905 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 28 from file lsppout
Data input seq. 8000 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9906 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 29 from file lsppout
Data input seq. 8001 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9907 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 30 from file lsppout
Data input seq. 8002 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9908 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 31 from file lsppout
Data input seq. 8003 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9909 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 32 from file lsppout
Data input seq. 8004 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9910 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 33 from file lsppout
Data input seq. 8005 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9911 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 34 from file lsppout
Data input seq. 8006 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9912 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 35 from file lsppout
Data input seq. 8007 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9913 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 36 from file lsppout
Data input seq. 8008 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9914 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 37 from file lsppout
Data input seq. 8009 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9915 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 38 from file lsppout
Data input seq. 8010 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9916 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 39 from file lsppout
Data input seq. 8011 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9917 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 40 from file lsppout
Data input seq. 8012 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9918 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 41 from file lsppout
Data input seq. 8013 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9919 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 42 from file lsppout
Data input seq. 8014 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9920 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 43 from file lsppout
Data input seq. 8015 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9921 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 44 from file lsppout
Data input seq. 8016 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9922 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 45 from file lsppout
Data input seq. 8017 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9923 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 46 from file lsppout
Data input seq. 8018 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9924 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 47 from file lsppout
Data input seq. 8019 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9925 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 48 from file lsppout
Data input seq. 8020 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9926 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 49 from file lsppout
Data input seq. 8021 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9927 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 50 from file lsppout
Data input seq. 8022 from file lsppout
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9928 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 51 from file lsppout
Data input seq. 8023 from file lsppout
Last one will be used
Warning -Duplicate keyword: more than 50 SOLID_ELEM use duplicate ID 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 52 from file lsppout
Data input seq. 8024 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=1 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 2 from file lsppout
Data input seq. 18246 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=2 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 3 from file lsppout
Data input seq. 18247 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=3 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 4 from file lsppout
Data input seq. 18248 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=4 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 5 from file lsppout
Data input seq. 18249 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=5 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 6 from file lsppout
Data input seq. 18250 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=6 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 7 from file lsppout
Data input seq. 18251 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=7 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 8 from file lsppout
Data input seq. 18252 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=8 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 9 from file lsppout
Data input seq. 18253 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=9 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 10 from file lsppout
Data input seq. 18254 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=10 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 11 from file lsppout
Data input seq. 18255 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=11 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 12 from file lsppout
Data input seq. 18256 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=12 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 13 from file lsppout
Data input seq. 18257 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=13 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 14 from file lsppout
Data input seq. 18258 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=14 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 15 from file lsppout
Data input seq. 18259 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=15 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 16 from file lsppout
Data input seq. 18260 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=16 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 17 from file lsppout
Data input seq. 18261 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=17 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 18 from file lsppout
Data input seq. 18262 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=18 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 19 from file lsppout
Data input seq. 18263 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=19 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 20 from file lsppout
Data input seq. 18264 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=20 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 21 from file lsppout
Data input seq. 18265 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=21 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 22 from file lsppout
Data input seq. 18266 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=22 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 23 from file lsppout
Data input seq. 18267 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=23 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 24 from file lsppout
Data input seq. 18268 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=24 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 25 from file lsppout
Data input seq. 18269 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=25 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 26 from file lsppout
Data input seq. 18270 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=26 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 27 from file lsppout
Data input seq. 18271 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=27 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 28 from file lsppout
Data input seq. 18272 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=28 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 29 from file lsppout
Data input seq. 18273 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=29 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 30 from file lsppout
Data input seq. 18274 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=30 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 31 from file lsppout
Data input seq. 18275 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=31 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 32 from file lsppout
Data input seq. 18276 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=32 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 33 from file lsppout
Data input seq. 18277 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=33 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 34 from file lsppout
Data input seq. 18278 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=34 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 35 from file lsppout
Data input seq. 18279 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=35 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 36 from file lsppout
Data input seq. 18280 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=36 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 37 from file lsppout
Data input seq. 18281 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=37 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 38 from file lsppout
Data input seq. 18282 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=38 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 39 from file lsppout
Data input seq. 18283 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=39 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 40 from file lsppout
Data input seq. 18284 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=40 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 41 from file lsppout
Data input seq. 18285 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=41 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 42 from file lsppout
Data input seq. 18286 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=42 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 43 from file lsppout
Data input seq. 18287 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=43 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 44 from file lsppout
Data input seq. 18288 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=44 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 45 from file lsppout
Data input seq. 18289 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=45 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 46 from file lsppout
Data input seq. 18290 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=46 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 47 from file lsppout
Data input seq. 18291 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=47 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 48 from file lsppout
Data input seq. 18292 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=48 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 49 from file lsppout
Data input seq. 18293 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=49 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 50 from file lsppout
Data input seq. 18294 from file lsppout
Last one will be used
Warning -Duplicate keyword: NODE input with ID=50 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 51 from file lsppout
Data input seq. 18295 from file lsppout
Last one will be used
Warning -Duplicate keyword: more than 50 NODE use duplicate ID 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key
Data input seq. 52 from file lsppout
Data input seq. 18296 from file lsppout
Last one will be used
Time to process element data = 1.812 seconds
Finished reading model
displayentity Set Node off all
displayentity Set Node on 2
displayentity Set Node off all
displayentity Set Node on 1
home
displayentity Set Node off all
displayentity Set Node on 2
pan 1.988225 -11.929352;
zoomhere 0.029309 -0.195714 1.250000;
zoomhere 0.029309 -0.195714 1.562500;
zoomhere 0.029309 -0.195714 1.953125;
zoomhere 0.030007 -0.201429 2.441406;
zoomhere 0.033496 -0.220000 1.953125;
zoomhere 0.033496 -0.220000 1.562500;
zoomhere 0.033496 -0.220000 1.250000;
zoomhere 0.033496 -0.220000 1.000000;
zoomhere 0.033496 -0.218571 0.800000;
zoomhere 0.030705 -0.212857 0.640000;
zoomhere 0.027913 -0.201429 0.512000;
zoomhere -0.009072 -0.064286 0.409600;
zoomhere -0.019539 -0.062857 0.327680;
zoomhere -0.027913 -0.064286 0.262144;
zoomhere -0.037683 -0.067143 0.209715;
pan 6.960595 -18.435768;
zoomhere 0.260293 -0.281429 0.262144;
zoomhere 0.260991 -0.284286 0.327680;
zoomhere 0.261689 -0.285714 0.409600;
zoomhere 0.262387 -0.287143 0.512000;
zoomhere 0.262387 -0.287143 0.640000;
zoomhere 0.262387 -0.290000 0.800000;
zoomhere 0.262387 -0.291429 1.000000;
zoomhere 0.260991 -0.292857 1.250000;
zoomhere 0.260293 -0.292857 1.562500;
zoomhere 0.259595 -0.292857 1.250000;
zoomhere 0.255408 -0.287143 1.562500;
pan -11.162203 11.030842;
zoomhere 0.133985 0.148571 1.250000;
zoomhere 0.133985 0.148571 1.000000;
zoomhere 0.133985 0.147143 0.800000;
zoomhere 0.133985 0.147143 0.640000;
zoomhere 0.133287 0.142857 0.512000;
zoomhere 0.132589 0.141429 0.409600;
zoomhere 0.131891 0.140000 0.327680;
zoomhere 0.130495 0.135714 0.262144;
displayentity Set Node off all
displayentity Set Node on 1
displayentity Set Node off all
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
