openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\structure2_test.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.250 seconds
Warning - SET_NODE 1 not found:
  Referenced in *BOUNDARY_SPC_SET ID = 1
Time to process element data = 0.062 seconds
Finished reading model
home
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
