openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\X-optimization\structure.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.125 seconds
Time to process element data = 0.062 seconds
Finished reading model
displayentity Set Node off all
displayentity Set Node on 1
displayentity Set Node off all
displayentity Set Node off all
displayentity Set Node on 2
displayentity Set Node off all
displayentity Set Node off all
displayentity Set Node on 1
displayentity Set Node off all
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
