openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\Old\structure2_test.k"
save keywordversion 2
save keywordversion 12
LS-PrePost encounters an error when open C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\Old\bcinfo.k
because the path is not found
Error - Include File bcinfo.k Not open
  Error occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\Old\structure2_test.k line # 239
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
