openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\Composites\mesh_ply_ball.key"
Time to read keyword file = 1.438 seconds
Warning - SECTION 1 not found:
  Referenced in *PART ID = 2
Warning - MAT 2 not found:
  Referenced in *PART ID = 2
Warning - EOS 1 not found:
  Referenced in *PART ID = 2
Warning - SECTION 1 not found:
  Referenced in *PART ID = 3
Warning - MAT 2 not found:
  Referenced in *PART ID = 3
Warning - EOS 1 not found:
  Referenced in *PART ID = 3
Warning - SECTION 1 not found:
  Referenced in *PART ID = 4
Warning - MAT 2 not found:
  Referenced in *PART ID = 4
Warning - EOS 1 not found:
  Referenced in *PART ID = 4
Warning - SECTION 1 not found:
  Referenced in *PART ID = 5
Warning - MAT 2 not found:
  Referenced in *PART ID = 5
Warning - EOS 1 not found:
  Referenced in *PART ID = 5
Time to process element data = 0.688 seconds
Finished reading model
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
