openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\ball_up_study\structure.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.250 seconds
Time to process element data = 0.000 seconds
Finished reading model
home
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
.8\lsppconf
