bgstyle fade
C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\6.7\d3plot"
Reading binary plot files
DES Format: version 2 detected!
Finished reading model
ac
home
mesh
mesh
state -1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
state +1;
anim forward
wire
wire
shad
mesh
zoomhere 0.145150 -0.074286 0.800000;
zoomhere 0.213538 -0.017143 0.640000;
pan 45.129066 -0.157366;
state +1;
mesh
state -1;
state +1;
measure select 1
genselect target element
measure type 11
genselect target part
genselect part add part 2/0 
Solid PART ID= 2
Volume of Solid Part #2 = 153.789
measure select 0
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
