openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\mono2\MJC.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.219 seconds
Time to process element data = 0.062 seconds
Finished reading model
home
measure select 1
genselect target element
measure type 11
genselect target part
genselect part add part 1/0 
Solid PART ID= 1
Volume of Solid Part #1 = 32.9996
measure select 0
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
