save keywordversion 2
save keywordversion 12
Time to read keyword file = 1.156 seconds
Warning -Duplicate keyword: EOS input with ID=3 
  Warning occurs in file C:\Users\Kayleigh\Documents\HVI share\HVI\k-files\S7.k
Last one will be used
Warning - MAT 8 not found:
  Referenced in *PART ID = 1
Warning - EOS 6 not found:
  Referenced in *PART ID = 1
Warning - MAT 8 not found:
  Referenced in *PART ID = 10
Warning - EOS 6 not found:
  Referenced in *PART ID = 10
Message 0
Time to read keyword file = 1.188 seconds
Message 0
Time to read keyword file = 1.125 seconds
Message 0
Time to read keyword file = 1.188 seconds
Message 0
