openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\test_files\structure2_test.key"
save keywordversion 2
save keywordversion 12
LS-PrePost encounters an error when open C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\test_files\mesh.key
because the path is not found
Error - Include File mesh.key Not open
  Error occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\test_files\structure2_test.key line # 217
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
