bgstyle fade
C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\X-optimization2\d3plot"
Reading binary plot files
DES Format: version 2 detected!
Finished reading model
ac
home
anim forward
ac
gtime 3
ID=3 pt:=31, abs=2.200023e-05, ord=8.313905e+05
gtime 3
ID=3 pt:=31, abs=2.200023e-05, ord=8.313905e+05
gtime 2
ID=2 pt:=31, abs=2.200023e-05, ord=3.447406e+03
anim stop; state 21;
state 1;
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
