openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\old\structure.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.156 seconds
Time to process element data = 0.031 seconds
Finished reading model
home
zoomhere 0.092308 -0.160000 0.800000;
zoomhere 0.088811 -0.151429 0.640000;
pan 4.787657 -1.057744;
zoomhere 0.011888 0.024286 0.512000;
pan 3.473833 -0.501037;
zoomhere 0.013287 0.035714 0.640000;
pan 1.714642 0.278352;
save keywordabsolute 0
save keywordbylongfmt 0
save keywordbyi10fmt 0
save keyword subsysfilename 1 "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\old\structure.key"
save keyword subsysfilename 2 "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\old\mesh_ball_target.key"
save keyword subsysfilename 3 "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\old\mesh_wall.key"
save keyword bysubsystem
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
mhere 0.189510 -0.041429 0.262144;
zoomhere 0.189510 -0.041429 0.327680;
zoomhere 0.189510 -0.041429 0.409600;
zoomhere 0.189510 -0.041429 0.512000;
zoomhere 0.189510 -0.041429 0.640000;
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
