openc keyword "C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key"
save keywordversion 12
Time to read keyword file = 0.312 seconds
Warning -Duplicate keyword: SOLID_ELEM input with ID=1 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 2 from file mesh_ball_target.key
Data input seq. 1858 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=2 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 3 from file mesh_ball_target.key
Data input seq. 1859 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=3 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 4 from file mesh_ball_target.key
Data input seq. 1860 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=4 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 5 from file mesh_ball_target.key
Data input seq. 1861 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=5 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 6 from file mesh_ball_target.key
Data input seq. 1862 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=6 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 7 from file mesh_ball_target.key
Data input seq. 1863 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=7 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 8 from file mesh_ball_target.key
Data input seq. 1864 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=8 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 9 from file mesh_ball_target.key
Data input seq. 1865 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=9 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 10 from file mesh_ball_target.key
Data input seq. 1866 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=10 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 11 from file mesh_ball_target.key
Data input seq. 1867 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=11 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 12 from file mesh_ball_target.key
Data input seq. 1868 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=12 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 13 from file mesh_ball_target.key
Data input seq. 1869 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=13 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 14 from file mesh_ball_target.key
Data input seq. 1870 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=14 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 15 from file mesh_ball_target.key
Data input seq. 1871 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=15 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 16 from file mesh_ball_target.key
Data input seq. 1872 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=16 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 17 from file mesh_ball_target.key
Data input seq. 1873 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=17 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 18 from file mesh_ball_target.key
Data input seq. 1874 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=18 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 19 from file mesh_ball_target.key
Data input seq. 1875 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=19 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 20 from file mesh_ball_target.key
Data input seq. 1876 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=20 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 21 from file mesh_ball_target.key
Data input seq. 1877 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=21 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 22 from file mesh_ball_target.key
Data input seq. 1878 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=22 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 23 from file mesh_ball_target.key
Data input seq. 1879 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=23 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 24 from file mesh_ball_target.key
Data input seq. 1880 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=24 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 25 from file mesh_ball_target.key
Data input seq. 1881 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=25 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 26 from file mesh_ball_target.key
Data input seq. 1882 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=26 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 27 from file mesh_ball_target.key
Data input seq. 1883 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=27 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 28 from file mesh_ball_target.key
Data input seq. 1884 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=28 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 29 from file mesh_ball_target.key
Data input seq. 1885 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=29 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 30 from file mesh_ball_target.key
Data input seq. 1886 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=30 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 31 from file mesh_ball_target.key
Data input seq. 1887 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=31 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 32 from file mesh_ball_target.key
Data input seq. 1888 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=32 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 33 from file mesh_ball_target.key
Data input seq. 1889 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=33 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 34 from file mesh_ball_target.key
Data input seq. 1890 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=34 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 35 from file mesh_ball_target.key
Data input seq. 1891 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=35 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 36 from file mesh_ball_target.key
Data input seq. 1892 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=36 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 37 from file mesh_ball_target.key
Data input seq. 1893 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=37 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 38 from file mesh_ball_target.key
Data input seq. 1894 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=38 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 39 from file mesh_ball_target.key
Data input seq. 1895 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=39 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 40 from file mesh_ball_target.key
Data input seq. 1896 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=40 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 41 from file mesh_ball_target.key
Data input seq. 1897 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=41 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 42 from file mesh_ball_target.key
Data input seq. 1898 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=42 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 43 from file mesh_ball_target.key
Data input seq. 1899 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=43 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 44 from file mesh_ball_target.key
Data input seq. 1900 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=44 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 45 from file mesh_ball_target.key
Data input seq. 1901 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=45 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 46 from file mesh_ball_target.key
Data input seq. 1902 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=46 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 47 from file mesh_ball_target.key
Data input seq. 1903 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=47 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 48 from file mesh_ball_target.key
Data input seq. 1904 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=48 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 49 from file mesh_ball_target.key
Data input seq. 1905 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=49 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 50 from file mesh_ball_target.key
Data input seq. 1906 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SOLID_ELEM input with ID=50 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 51 from file mesh_ball_target.key
Data input seq. 1907 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: more than 50 SOLID_ELEM use duplicate ID 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 52 from file mesh_ball_target.key
Data input seq. 1908 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: PART input with ID=3 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 6 from file mesh_ball_target.key
Data input seq. 8 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SET_NODE input with ID=1 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 3 from file mesh_ball_target.key
Data input seq. 6 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SET_NODE input with ID=2 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 4 from file mesh_ball_target.key
Data input seq. 7 from file mesh_wall.key
Last one will be used
Warning -Duplicate keyword: SET_NODE input with ID=3 
  Warning occurs in file C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\structure.key
Data input seq. 5 from file mesh_ball_target.key
Data input seq. 8 from file mesh_wall.key
Last one will be used
Time to process element data = 0.875 seconds
Finished reading model
quat 0.405509 -0.288761 -0.461269 0.734446;
home
zoomhere 0.179344 -0.241283 0.800000;
zoomhere 0.166085 -0.239888 0.640000;
zoomhere 0.154222 -0.239888 0.512000;
zoomhere 0.145150 -0.238494 0.409600;
zoomhere 0.143754 -0.237099 0.512000;
zoomhere 0.140963 -0.237099 0.409600;
zoomhere 0.136776 -0.235704 0.327680;
zoomhere 0.127704 -0.230126 0.262144;
zoomhere 0.087230 -0.225941 0.209715;
zoomhere 0.086532 -0.227336 0.167772;
zoomhere 0.086532 -0.227336 0.134218;
zoomhere 0.086532 -0.227336 0.107374;
zoomhere 0.112352 -0.281729 0.134217;
zoomhere 0.112352 -0.280335 0.167771;
zoomhere 0.112352 -0.280335 0.209714;
zoomhere 0.112352 -0.280335 0.262142;
zoomhere 0.113747 -0.306834 0.327678;
pan 29.060474 -27.073677;
zoomhere 0.157013 -0.184100 0.262142;
zoomhere 0.157013 -0.184100 0.209714;
zoomhere 0.157013 -0.184100 0.167771;
zoomhere 0.157013 -0.184100 0.134217;
zoomhere 0.157013 -0.184100 0.107374;
zoomhere 0.157013 -0.184100 0.085899;
zoomhere 0.149337 -0.186890 0.107374;
zoomhere 0.147941 -0.189679 0.134217;
zoomhere 0.147244 -0.191074 0.167771;
zoomhere 0.146546 -0.191074 0.209714;
zoomhere 0.146546 -0.191074 0.262142;
zoomhere 0.146546 -0.191074 0.327678;
zoomhere 0.146546 -0.191074 0.409597;
zoomhere 0.146546 -0.191074 0.511996;
zoomhere 0.146546 -0.191074 0.639995;
zoomhere 0.333566 -0.235704 0.511996;
zoomhere 0.333566 -0.235704 0.409597;
zoomhere 0.332868 -0.235704 0.327678;
zoomhere 0.332170 -0.235704 0.262142;
zoomhere 0.331472 -0.235704 0.209714;
zoomhere 0.314027 -0.252441 0.262142;
zoomhere 0.313329 -0.252441 0.327678;
measure select 1
measure select 0
ident select 1
genselect target node
zoomhere 0.278437 -0.227336 0.262142;
zoomhere 0.272854 -0.224547 0.209714;
zoomhere 0.270761 -0.224547 0.167771;
zoomhere 0.266574 -0.224547 0.134217;
zoomhere 0.265178 -0.224547 0.107374;
zoomhere 0.214934 -0.224547 0.085899;
zoomhere 0.214934 -0.224547 0.068719;
zoomhere 0.214934 -0.224547 0.054975;
zoomhere 0.214934 -0.224547 0.043980;
Coincident nodes found. Select node ID
Coincident nodes found. Select node ID
genselect node add node 22562/0 
NODE ID= 22562 ,  xyz= 131, -38.7071, 0.25
zoomhere 0.224006 -0.348675 0.054975;
zoomhere 0.224006 -0.348675 0.068719;
zoomhere 0.224006 -0.348675 0.085899;
zoomhere 0.224006 -0.348675 0.107374;
zoomhere 0.224006 -0.348675 0.134217;
zoomhere 0.224006 -0.348675 0.167771;
zoomhere 0.224006 -0.348675 0.209714;
zoomhere 0.224006 -0.348675 0.262142;
zoomhere 0.224006 -0.348675 0.327678;
zoomhere 0.228890 -0.348675 0.409597;
zoomhere 0.228890 -0.348675 0.511996;
zoomhere 0.228890 -0.348675 0.639995;
zoomhere 0.228890 -0.348675 0.799994;
zoomhere 0.228890 -0.348675 0.999992;
zoomhere 0.228890 -0.348675 1.249990;
zoomhere 0.228890 -0.348675 0.999992;
zoomhere 0.228890 -0.348675 0.799994;
zoomhere 0.227495 0.338912 0.639995;
zoomhere 0.226797 0.351464 0.511996;
zoomhere 0.224703 0.359833 0.409597;
zoomhere 0.224703 0.359833 0.511996;
zoomhere 0.223308 0.364017 0.409597;
zoomhere 0.218423 0.377964 0.327678;
zoomhere 0.215632 0.394700 0.262142;
zoomhere 0.213538 0.405858 0.209714;
zoomhere 0.212142 0.429568 0.167771;
zoomhere 0.247034 0.373780 0.134217;
zoomhere 0.247034 0.369596 0.107374;
zoomhere 0.247034 0.368201 0.085899;
zoomhere 0.247034 0.366806 0.068719;
zoomhere 0.247034 0.364017 0.054975;
zoomhere 0.246336 0.359833 0.043980;
Coincident nodes found. Select node ID
genselect node add node 24448/0 
NODE ID= 24448 ,  xyz= 131, 38.7071, 0.25
zoomhere 0.294487 0.165969 0.054975;
zoomhere 0.293091 0.165969 0.068719;
zoomhere 0.293091 0.165969 0.085899;
zoomhere 0.293091 0.165969 0.107374;
zoomhere 0.293091 0.165969 0.134217;
zoomhere 0.293091 0.165969 0.167771;
ident select 0
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
