bgstyle fade
C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\2P-X-opt\4.6\d3plot"
Reading binary plot files
DES Format: version 2 detected!
Finished reading model
ac
home
mesh
zoomhere 0.041870 -0.041429 0.800000;
zoomhere 0.041870 -0.041429 0.640000;
anim forward
animatemode 1
state +1;
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
