open command "C:\Users\Kayleigh\Documents\HVI share\HVI\LS-OPT_test\2P-X-3D\create_mesh_wall.cfile"
bgstyle fade
openc
parameter y17=0.0000000000000000e+00
parameter y18=0.0000000000000000e+00
parameter x11=1.3050000000000000e+02
parameter x2=1.0050000000000000e+02
parameter x4=1.3050000000000000e+02
parameter x9=1.0050000000000000e+02
parameter x1=1.0050000000000000e+02
parameter x5=1.3050000000000000e+02
parameter y1=-3.7500000000000000e+01
parameter y5=-3.7500000000000000e+01
parameter y6=-3.7500000000000000e+01
parameter x10=1.2147613700707882e+02
parameter x12=1.1398984001781560e+02
parameter x13=1.1754794637980370e+02
parameter x17=1.0761300199870217e+02
parameter x18=1.2822137259651083e+02
parameter x3=1.1542260667065059e+02
parameter x7=1.0764098146265671e+02
parameter x8=1.2885032320897500e+02
parameter y10=-1.3343180867369414e+01
parameter y12=-9.1405086764815486e+00
parameter y13=-2.0332484164421039e+01
parameter y3=-2.8326536171746216e+01
parameter y7=-3.5105439576107486e+01
parameter y8=-3.5397798451868098e+01
parameter y11=-1.3161928293560935e+01
parameter y2=-1.6645128564987338e+01
parameter y4=-1.6626146592272253e+01
parameter y9=-1.3463099599001639e+01
parameter x6=1.1510910207390090e+02
parameter x14=1.0050000000000000e+02
parameter x15=1.2147613700707882e+02
parameter x16=1.3050000000000000e+02
parameter x19=1.0050000000000000e+02
parameter x20=1.1542260667065059e+02
parameter x21=1.3050000000000000e+02
parameter x22=1.1398984001781560e+02
parameter x23=1.1754794637980370e+02
parameter x27=1.0764098146265671e+02
parameter x28=1.2885032320897500e+02
parameter y14=1.3463099599001639e+01
parameter y15=1.3343180867369414e+01
parameter y16=1.3161928293560935e+01
parameter y19=1.6645128564987338e+01
parameter y20=2.8326536171746216e+01
parameter y21=1.6626146592272253e+01
parameter y22=9.1405086764815486e+00
parameter y23=2.0332484164421039e+01
parameter y27=3.5105439576107486e+01
parameter y28=3.5397798451868098e+01
parameter x24=1.0050000000000000e+02
parameter x25=1.1510910207390090e+02
parameter x26=1.3050000000000000e+02
parameter y24=3.7500000000000000e+01
parameter y25=3.7500000000000000e+01
parameter y26=3.7500000000000000e+01
End of command file!
cemptymodel
genselect target edge
genselect clear
mesh2d createrpoint 1 1.0050000000000000e+02 -3.7500000000000000e+01 
mesh2d createrpoint 2 1.0050000000000000e+02 -1.6645128564987338e+01 
mesh2d createrpoint 3 1.1542260667065059e+02 -2.8326536171746216e+01 
mesh2d createrpoint 4 1.3050000000000000e+02 -1.6626146592272253e+01 
mesh2d createrpoint 5 1.3050000000000000e+02 -3.7500000000000000e+01 
mesh2d createrpoint 6 1.1510910207390090e+02 -3.7500000000000000e+01 
mesh2d createrpoint 7 1.0764098146265671e+02 -3.5105439576107486e+01 
mesh2d createrpoint 8 1.2885032320897500e+02 -3.5397798451868098e+01 
mesh2d createrpoint 9 1.0050000000000000e+02 -1.3463099599001639e+01 
mesh2d createrpoint 10 1.2147613700707882e+02 -1.3343180867369414e+01 
mesh2d createrpoint 11 1.3050000000000000e+02 -1.3161928293560935e+01 
mesh2d createrpoint 12 1.1398984001781560e+02 -9.1405086764815486e+00 
mesh2d createrpoint 13 1.1754794637980370e+02 -2.0332484164421039e+01 
mesh2d createrpoint 14 1.0050000000000000e+02 1.3463099599001639e+01 
mesh2d createrpoint 15 1.2147613700707882e+02 1.3343180867369414e+01 
mesh2d createrpoint 16 1.3050000000000000e+02 1.3161928293560935e+01 
mesh2d createrpoint 17 1.0761300199870217e+02 0.0000000000000000e+00 
mesh2d createrpoint 18 1.2822137259651083e+02 0.0000000000000000e+00 
mesh2d createrpoint 19 1.0050000000000000e+02 1.6645128564987338e+01 
mesh2d createrpoint 20 1.1542260667065059e+02 2.8326536171746216e+01 
mesh2d createrpoint 21 1.3050000000000000e+02 1.6626146592272253e+01 
mesh2d createrpoint 22 1.1398984001781560e+02 9.1405086764815486e+00 
mesh2d createrpoint 23 1.1754794637980370e+02 2.0332484164421039e+01 
mesh2d createrpoint 24 1.0050000000000000e+02 3.7500000000000000e+01 
mesh2d createrpoint 25 1.1510910207390090e+02 3.7500000000000000e+01 
mesh2d createrpoint 26 1.3050000000000000e+02 3.7500000000000000e+01 
mesh2d createrpoint 27 1.0764098146265671e+02 3.5105439576107486e+01 
mesh2d createrpoint 28 1.2885032320897500e+02 3.5397798451868098e+01 
mesh2d acen
mesh2d createline 29 1 7
ac
mesh2d createline 30 2 7
mesh2d createline 31 3 7
mesh2d createline 32 6 7
mesh2d createline 33 6 8
mesh2d createline 34 3 8
mesh2d createline 35 4 8
mesh2d createline 36 5 8
mesh2d createline 37 1 2
mesh2d createline 38 4 5
mesh2d createline 39 2 12
mesh2d createline 40 9 12
mesh2d createline 41 10 12
mesh2d createline 42 3 12
mesh2d createline 43 3 13
mesh2d createline 44 10 13
mesh2d createline 45 11 13
mesh2d createline 46 4 13
mesh2d createline 47 9 2
mesh2d createline 48 11 4
mesh2d createline 49 9 17
mesh2d createline 50 14 17
mesh2d createline 51 15 17
mesh2d createline 52 10 17
mesh2d createline 53 10 18
mesh2d createline 54 15 18
mesh2d createline 55 16 18
mesh2d createline 56 11 18
mesh2d createline 57 9 14
mesh2d createline 58 16 11
mesh2d createline 59 14 22
mesh2d createline 60 19 22
mesh2d createline 61 20 22
mesh2d createline 62 15 22
mesh2d createline 63 15 23
mesh2d createline 64 20 23
mesh2d createline 65 21 23
mesh2d createline 66 16 23
mesh2d createline 67 14 19
mesh2d createline 68 21 16
mesh2d createline 69 19 27
mesh2d createline 70 24 27
mesh2d createline 71 25 27
mesh2d createline 72 20 27
mesh2d createline 73 20 28
mesh2d createline 74 25 28
mesh2d createline 75 26 28
mesh2d createline 76 21 28
mesh2d createline 77 19 24
mesh2d createline 78 26 21
mesh2d sbdown
home
ac
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  2e
genselect occobject add occobject  1e
genselect occobject add occobject  9e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 2e 1 9
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  8e
genselect occobject add occobject  7e
genselect occobject add occobject  10e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 8e 7 10
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  12e
genselect occobject add occobject  11e
genselect occobject add occobject  19e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 12e 11 19
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  18e
genselect occobject add occobject  17e
genselect occobject add occobject  20e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 18e 17 20
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  22e
genselect occobject add occobject  21e
genselect occobject add occobject  29e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 22e 21 29
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  28e
genselect occobject add occobject  27e
genselect occobject add occobject  30e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 28e 27 30
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  32e
genselect occobject add occobject  31e
genselect occobject add occobject  39e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 32e 31 39
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  38e
genselect occobject add occobject  37e
genselect occobject add occobject  40e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 38e 37 40
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  42e
genselect occobject add occobject  41e
genselect occobject add occobject  49e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 42e 41 49
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  48e
genselect occobject add occobject  47e
genselect occobject add occobject  50e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 48e 47 50
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  4e
genselect occobject add occobject  3e
genselect occobject add occobject  6e
genselect occobject add occobject  5e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 4e 3 6 5
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  3e
genselect occobject add occobject  14e
genselect occobject add occobject  11e
genselect occobject add occobject  2e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 3e 14 11 2
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  7e
genselect occobject add occobject  18e
genselect occobject add occobject  15e
genselect occobject add occobject  6e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 7e 18 15 6
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  14e
genselect occobject add occobject  13e
genselect occobject add occobject  16e
genselect occobject add occobject  15e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 14e 13 16 15
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  13e
genselect occobject add occobject  24e
genselect occobject add occobject  21e
genselect occobject add occobject  12e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 13e 24 21 12
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  17e
genselect occobject add occobject  28e
genselect occobject add occobject  25e
genselect occobject add occobject  16e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 17e 28 25 16
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  24e
genselect occobject add occobject  23e
genselect occobject add occobject  26e
genselect occobject add occobject  25e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 24e 23 26 25
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  23e
genselect occobject add occobject  34e
genselect occobject add occobject  31e
genselect occobject add occobject  22e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 23e 34 31 22
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  27e
genselect occobject add occobject  38e
genselect occobject add occobject  35e
genselect occobject add occobject  26e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 27e 38 35 26
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  34e
genselect occobject add occobject  33e
genselect occobject add occobject  36e
genselect occobject add occobject  35e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 34e 33 36 35
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  33e
genselect occobject add occobject  44e
genselect occobject add occobject  41e
genselect occobject add occobject  32e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 33e 44 41 32
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  37e
genselect occobject add occobject  48e
genselect occobject add occobject  45e
genselect occobject add occobject  36e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 37e 48 45 36
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  44e
genselect occobject add occobject  43e
genselect occobject add occobject  46e
genselect occobject add occobject  45e
offsetgeom  planeedgewire 0.375 invert tags 2 0 0 44e 43 46 45
genselect clear
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
genselect occobject add occobject  8e
genselect occobject add occobject  5e
genselect occobject add occobject  4e
genselect occobject add occobject  1e
genselect occobject add occobject  9e
genselect occobject add occobject  19e
genselect occobject add occobject  29e
genselect occobject add occobject  39e
genselect occobject add occobject  49e
genselect occobject add occobject  42e
genselect occobject add occobject  43e
genselect occobject add occobject  46e
genselect occobject add occobject  47e
genselect occobject add occobject  50e
genselect occobject add occobject  40e
genselect occobject add occobject  30e
genselect occobject add occobject  20e
genselect occobject add occobject  10e
offsetgeom planeedgewire 0.375 tags 2 0 0 8e 5 4 1 9 19 29 39 49 42 43 46 47 50 40 30 20 10 
genselect clear
genselect clear
geomag del 1e 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 //
genselect target occobject
occfilter clear
occfilter add Edge Wire
undogeom enter
nlmesh2 switch 4 1 0.2500
nlmesh2 sizepara 0 0.25000
NLine mesh command failed.
genselect clear
nlmesh2 clearsel
nlmesh2 clearsel
genselect occobject add occobjectcheck  24w
nlmesh2 seledge 24w 0 1
genselect clear
nlmesh2 clearsel
nlmesh2 clearsel
genselect occobject add occobjectcheck  1w 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
nlmesh2 seledge 1w 0 1
nlmesh2 seledge 2w 0 1
nlmesh2 seledge 3w 0 1
nlmesh2 seledge 4w 0 1
nlmesh2 seledge 5w 0 1
nlmesh2 seledge 6w 0 1
nlmesh2 seledge 7w 0 1
nlmesh2 seledge 8w 0 1
nlmesh2 seledge 9w 0 1
nlmesh2 seledge 10w 0 1
nlmesh2 seledge 11w 0 1
nlmesh2 seledge 12w 0 1
nlmesh2 seledge 13w 0 1
nlmesh2 seledge 14w 0 1
nlmesh2 seledge 15w 0 1
nlmesh2 seledge 16w 0 1
nlmesh2 seledge 17w 0 1
nlmesh2 seledge 18w 0 1
nlmesh2 seledge 19w 0 1
nlmesh2 seledge 20w 0 1
nlmesh2 seledge 21w 0 1
nlmesh2 seledge 22w 0 1
nlmesh2 seledge 23w 0 1
nlmesh2 seledge 24w 0 1
nlmesh2 mesh 1 4 0
nlmesh2 accept 1
genselect clear
genselect clear
nlmesh2 clearsel
nlmesh2 clearsel
genselect target edge
genselect target segment
genselect element add part 1/0
elgenerate solid solidfacedrag 2 30000000 75.0000 300 0 0 0 0 0 4
genselect clear
genselect clear
elgenerate accept
partdata delete 1
delelement unrefn 1
delelement unrefn 0
geomag delnoundo 1w 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
KEYWORD INPUT 1
renumber clean
renumber offset 0
renumber setkind NODE 9999999
renumber setrange 1 2612680 2612680
renumber renumkind 170
renumber keyword
renum occupant models
renum occupant models
Invalid command renum!
renumber clean
renumber offset 0
renumber setkind SOLID_ELEM 9999999
renumber setrange 30000000 31977599 1977600
renumber renumkind 133
renumber keyword
renum occupant models
renum occupant models
Invalid command renum!
genselect target node
genselect clear
genselect clear
Coincident nodes found. Select node ID
Invalid command coincident!
genselect node add box in 100.00010 -38.40523 -0.00010 99.99990 -38.40543 75.00010
genselect node add box in 100.00010 38.40543 -0.00010 99.99990 38.40523 75.00010
genselect node add box in 100.00010 1000.00000 -0.00010 99.99990 -1000.00000 0.00010
genselect node add box in 100.00010 1000.00000 74.99990 99.99990 -1000.00000 75.00010
setnode createset 5 1 0 0 0 0 "Fix XY Wall" 
genselect clear
save keyword "mesh_wall.key"
exit
Save Config. parameters to file C:\Users\Kayleigh\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
