open keyword "C:\Users\Kayleigh\Documents\CASA\part2_composites\lowv_fem_des\structure.key"
save keywordversion 2
save keywordversion 12
Time to read keyword file = 0.953 seconds
Time to process element data = 0.352 seconds
Finished reading model
selectentity None
open keyword "C:\Users\Kayleigh\Documents\CASA\part2_composites\lowv_fem_des\LSOPT\structure.key"
Time to read keyword file = 0.875 seconds
Time to process element data = 0.320 seconds
Finished reading model
save keywordabsolute 0
save keywordbylongfmt 0
save keywordbyi10fmt 0
save keyword specialsubsystem "C:\Users\Kayleigh\Documents\CASA\part2_composites\lowv_fem_des\LSOPT\structure.key" 1
Save Config. parameters to file C:\Users\Kayleigh\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
