bgstyle fade
C:\Users\s148946\OneDrive\Documenten\Internship\Project\Shared folder\HVI\GitHub\LS-OPT_test\X-optimization\working\d3plot"
Reading binary plot files
DES Format: version 2 detected!
Finished reading model
ac
home
anim forward
anim stop; state 2;
gtime 2
ID=2 pt:=31, abs=2.200085e-05, ord=3.063556e+03
state -1;
state -1;
state -1;
state +1;
anim forward
anim stop; state 10;
gtime 2
ID=2 pt:=31, abs=2.200085e-05, ord=3.063556e+03
Save Config. parameters to file C:\Users\s148946\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
